# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pulse_recorder_mainwindow_design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 408)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnFileSelect = QtWidgets.QPushButton(self.centralwidget)
        self.btnFileSelect.setObjectName("btnFileSelect")
        self.horizontalLayout.addWidget(self.btnFileSelect)
        self.lineEditSaveFile = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSaveFile.setReadOnly(True)
        self.lineEditSaveFile.setObjectName("lineEditSaveFile")
        self.horizontalLayout.addWidget(self.lineEditSaveFile)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnStartSaving = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartSaving.setObjectName("btnStartSaving")
        self.verticalLayout_2.addWidget(self.btnStartSaving)
        self.btnStopSaving = QtWidgets.QPushButton(self.centralwidget)
        self.btnStopSaving.setEnabled(True)
        self.btnStopSaving.setObjectName("btnStopSaving")
        self.verticalLayout_2.addWidget(self.btnStopSaving)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelSavedCounts = QtWidgets.QLabel(self.groupBox_4)
        self.labelSavedCounts.setObjectName("labelSavedCounts")
        self.verticalLayout_8.addWidget(self.labelSavedCounts)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.checkBoxRetention = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBoxRetention.setObjectName("checkBoxRetention")
        self.verticalLayout_9.addWidget(self.checkBoxRetention)
        self.lineEditRetention = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditRetention.setEnabled(False)
        self.lineEditRetention.setObjectName("lineEditRetention")
        self.verticalLayout_9.addWidget(self.lineEditRetention)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEditHoldoff = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditHoldoff.sizePolicy().hasHeightForWidth())
        self.lineEditHoldoff.setSizePolicy(sizePolicy)
        self.lineEditHoldoff.setObjectName("lineEditHoldoff")
        self.verticalLayout_4.addWidget(self.lineEditHoldoff)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.btnZeroTimer = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnZeroTimer.sizePolicy().hasHeightForWidth())
        self.btnZeroTimer.setSizePolicy(sizePolicy)
        self.btnZeroTimer.setObjectName("btnZeroTimer")
        self.verticalLayout_2.addWidget(self.btnZeroTimer)
        self.btnPurgeMemory = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPurgeMemory.sizePolicy().hasHeightForWidth())
        self.btnPurgeMemory.setSizePolicy(sizePolicy)
        self.btnPurgeMemory.setObjectName("btnPurgeMemory")
        self.verticalLayout_2.addWidget(self.btnPurgeMemory)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.btnEnableSend = QtWidgets.QPushButton(self.centralwidget)
        self.btnEnableSend.setObjectName("btnEnableSend")
        self.verticalLayout_3.addWidget(self.btnEnableSend)
        self.btnDisableSend = QtWidgets.QPushButton(self.centralwidget)
        self.btnDisableSend.setObjectName("btnDisableSend")
        self.verticalLayout_3.addWidget(self.btnDisableSend)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.labelMemoryIndicator = QtWidgets.QLabel(self.groupBox_3)
        self.labelMemoryIndicator.setObjectName("labelMemoryIndicator")
        self.verticalLayout_7.addWidget(self.labelMemoryIndicator)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.barMemoryIndicator = QtWidgets.QProgressBar(self.groupBox_3)
        self.barMemoryIndicator.setProperty("value", 0)
        self.barMemoryIndicator.setOrientation(QtCore.Qt.Vertical)
        self.barMemoryIndicator.setObjectName("barMemoryIndicator")
        self.horizontalLayout_4.addWidget(self.barMemoryIndicator)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelCountRateIndicator = QtWidgets.QLabel(self.groupBox_2)
        self.labelCountRateIndicator.setObjectName("labelCountRateIndicator")
        self.verticalLayout_6.addWidget(self.labelCountRateIndicator)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnFileSelect.setText(_translate("MainWindow", "select save file"))
        self.btnStartSaving.setText(_translate("MainWindow", "start saving"))
        self.btnStopSaving.setText(_translate("MainWindow", "stop saving"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Saved counts:"))
        self.labelSavedCounts.setText(_translate("MainWindow", "0"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Coincidence filter interval:"))
        self.checkBoxRetention.setText(_translate("MainWindow", "Enable"))
        self.lineEditRetention.setText(_translate("MainWindow", "1s"))
        self.groupBox.setTitle(_translate("MainWindow", "Holdoff time:"))
        self.lineEditHoldoff.setText(_translate("MainWindow", "10ns"))
        self.btnZeroTimer.setText(_translate("MainWindow", "zero timer"))
        self.btnPurgeMemory.setText(_translate("MainWindow", "purge memory"))
        self.btnEnableSend.setText(_translate("MainWindow", "enable sending"))
        self.btnDisableSend.setText(_translate("MainWindow", "disable sending"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Memory used:"))
        self.labelMemoryIndicator.setText(_translate("MainWindow", "0\n"
"/32,000,000"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Count Rate:"))
        self.labelCountRateIndicator.setText(_translate("MainWindow", "0 cps"))

